# 1.0 Importando a biblioteca:

In [32]:
import numpy as np
from numpy.linalg import inv #biblioteca específica para Álgebra Linear

# 2.0 Representando uma matriz:

Para representar uma matriz, temos duas possibilidades: Arrays ou Matrix.

## 2.1 Array:

Essa é a primeira forma e a mais utilizada para escrever uma matriz. Utilizamos a ideia de vetores e podemos escrever uma matriz como um vetor multidimensional.

In [3]:
m1 = np.array([1,3])
m1

array([1, 3])

Repare que quando escrito com apenas um par de [], temos um vetor, olhe a dimensão:

In [4]:
m1.shape

(2,)

Se quisermos escrever uma matriz linha com duas colunas, precisamos dos dois pares:

In [5]:
m2 = np.array([
    [1,3]
])
m2

array([[1, 3]])

In [6]:
m2.shape

(1, 2)

## 2.2 Matriz:

Existe uma outra forma de escrever uma matriz, com a função matrix, porém ela é menos usada. Apenas para deixar registrada:

In [7]:
exemplo_1 = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
exemplo_1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Para verificar a sua dimensão:

In [8]:
exemplo_1.shape

(3, 3)

# 3.0 Operações com matrizes:

Para começar, vamos criar duas matrizes A e B para podermos ver na prática as operações.

In [9]:
# Criando a matriz A:

A = np.array([
    [1,2,3],
    [4,8,9],
    [0,-1,3.7]
])

# Criando a matriz B:

B = np.array([
    [9,8,-1],
    [0,3,7],
    [7,10,2]
])

# Vamos imprimir as matrizes para vermos:

print(f'''As matrizes A e B são:
{A} 

e 

{B}

, respectivamente''')

As matrizes A e B são:
[[ 1.   2.   3. ]
 [ 4.   8.   9. ]
 [ 0.  -1.   3.7]] 

e 

[[ 9  8 -1]
 [ 0  3  7]
 [ 7 10  2]]

, respectivamente


## 3.1 Soma e subtração:

In [10]:
soma = A + B
sub = A - B

print(f'''
A soma é 
{soma}

A subtração é 
{sub} ''')


A soma é 
[[10.  10.   2. ]
 [ 4.  11.  16. ]
 [ 7.   9.   5.7]]

A subtração é 
[[ -8.   -6.    4. ]
 [  4.    5.    2. ]
 [ -7.  -11.    1.7]] 


## 3.2 Multiplicação termo a termo:

Aqui vale ressaltar a diferença entre A*B e A@B, a primeira é a multiplicação termo a termo, enquanto a segunda é realmente o produto matricial.

In [11]:
termo_a_termo = A * B
termo_a_termo

array([[  9. ,  16. ,  -3. ],
       [  0. ,  24. ,  63. ],
       [  0. , -10. ,   7.4]])

Uma outra maneira de obter o mesmo resultado é com a função np.multiply(matriz1,matriz2)

In [12]:
termo_2 = np.multiply(A,B)
termo_2

array([[  9. ,  16. ,  -3. ],
       [  0. ,  24. ,  63. ],
       [  0. , -10. ,   7.4]])

## 3.3 Produto matricial:

In [13]:
produto = A@B
produto

array([[ 30. ,  44. ,  19. ],
       [ 99. , 146. ,  70. ],
       [ 25.9,  34. ,   0.4]])

Podemos fazer a multiplicação entre matrizes pela dunção np.dot(matriz1, matriz2)

In [27]:
produto_2 = np.dot(A,B)
produto_2

array([[ 30. ,  44. ,  19. ],
       [ 99. , 146. ,  70. ],
       [ 25.9,  34. ,   0.4]])

## 3.4 Traço de uma matriz:

In [30]:
A

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  8. ,  9. ],
       [ 0. , -1. ,  3.7]])

In [31]:
traco_A = np.trace(A)

print(f'O traço da matria A é {traco_A}.')

O traço da matria A é 12.7.


# 4.0 Tipos de matrizes:

## 4.1 Matriz linha:

In [14]:
linha = np.array([
    [1,2,3]
])
linha.shape

(1, 3)

In [15]:
print(linha)

[[1 2 3]]


## 4.2 Matriz coluna:

In [16]:
coluna = np.array([
    [1],
    [2],
    [0]
])
coluna.shape

(3, 1)

In [17]:
print(coluna)

[[1]
 [2]
 [0]]


## 4.3 Matriz diagonal:

Aqui, vale reforçar que temos uma função que facilita a escrita de matrizes diagonais:

In [18]:
diagonal = np.diag(
    [1,2,3]
)
diagonal.shape

(3, 3)

In [19]:
print(diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


## 4.4 Matriz Transposta:

In [20]:
A_t = np.transpose(A)
A_t

array([[ 1. ,  4. ,  0. ],
       [ 2. ,  8. , -1. ],
       [ 3. ,  9. ,  3.7]])

Uma outra maneira de calcular a transposta pelo Python é fazer o .T, assim:

In [21]:
B

array([[ 9,  8, -1],
       [ 0,  3,  7],
       [ 7, 10,  2]])

In [22]:
B_t = B.T
B_t

array([[ 9,  0,  7],
       [ 8,  3, 10],
       [-1,  7,  2]])

## 4.5 Matriz Nula:

In [23]:
N = np.zeros([2,3])

In [24]:
print(N)

[[0. 0. 0.]
 [0. 0. 0.]]


## 4.6 Matriz Identidade:

In [25]:
MI = np.identity(5)

In [26]:
print(MI)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 5.0 Matriz Inversa:

A biblioteca NumPy é realmente bastante completa e, portanto, temos uma função especial para encontrar a matriz inversa. Algo muito útil é que dentro da NumPy temos um pacote de
métodos disponíveis para trabalhar exclusivamente com álgebra linear. Esse pacote se chama (numpy.linalg). Dentro dele podemos encontrar a função para calcular a inversa de uma matriz (chamada de inv()).

In [33]:
inv_A = inv(A)

inv_A

array([[-12.86666667,   3.46666667,   2.        ],
       [  4.93333333,  -1.23333333,  -1.        ],
       [  1.33333333,  -0.33333333,   0.        ]])

# 6.0 Coletando os elementos de uma matriz:

## 6.1 Pegando um único elemento:

Para coletar cada elemento de uma matriz, temos que lembrar que temos uma lista, assim, basta passar o elemento que desejamos. Por exemplo:

In [35]:
# Vamos colocar a matriz A para podermos fazer a verificação

print(A)

[[ 1.   2.   3. ]
 [ 4.   8.   9. ]
 [ 0.  -1.   3.7]]


In [34]:
A11 = A[0,0] # é válido lembrar que começamos com 0 no python
A11

np.float64(1.0)

## 6.2 Para pegar uma linha inteira:

In [37]:
A_linha_1 = A[0,:]
A_linha_1

array([1., 2., 3.])

In [38]:
A_linha_2 = A[1,:]
A_linha_2

array([4., 8., 9.])

## 6.3 Para pegar uma coluna inteira:

In [45]:
A_coluna_1 = A[:,0]
A_coluna_1

array([1., 4., 0.])

In [47]:
A_coluna_2 = A[:,1]
A_coluna_2

array([ 2.,  8., -1.])

OBS.: Para Álgebra Linear, eu prefiro essa segunda forma quando você quer pensar explicitamente em vetores coluna.

In [48]:
A_vetor_coluna_1 = A[:,[0]]
A_vetor_coluna_1

array([[1.],
       [4.],
       [0.]])