# 1.0 Vetores:

É muito comum termos um conjunto de escalares, um vetor, e precisarmos executar operações de soma, divisão e/ou multiplicação de escalares com esses vetores. Vamos acompanhar o exemplo abaixo:

In [23]:
# Importando a biblioteca Numpy:

import numpy as np
from numpy.linalg import inv

In [14]:
# Dado o escalar a:

a = 3

# e o vetor

v = np.array([1,2,3])

print(v)

[1 2 3]


# 2.0 Operações com escalar:

## 2.1 Soma e subtração:

In [15]:
v1 = v + a
v1

array([4, 5, 6])

In [16]:
v2 = v - a
v2

array([-2, -1,  0])

## 2.2 Multiplicação:

In [17]:
v3 = a * v
v3

array([3, 6, 9])

## 2.3 Divisão:

In [18]:
v4 = v / a
v4

array([0.33333333, 0.66666667, 1.        ])

# 3.0 Operações entre vetores:

De maneira análoga, podemos fazer as operações entre vetores também. Assim, temos:

In [19]:
# Já conhecemos o vetor v, vamos criar o vetor  u:

u = np.array([7,8,0])
u

array([7, 8, 0])

Agora, vamos as operações:

In [20]:
soma = v + u
dif = v - u
mult = v * u

soma_2 = 3 * v - 5 * u

print(soma)
print(dif)
print(mult)
print(soma_2)

[ 8 10  3]
[-6 -6  3]
[ 7 16  0]
[-32 -34   9]
