# 1.0 Importando as bibliotecas:

In [1]:
import numpy as np
from numpy.linalg import inv

# 2.0 Determinantes:

Para calcular o determinante de uma matriz, basta usar a função linalg.det(A):

In [10]:
# Criando a matriz m1:

m1 = np.array([
    [1,5,9],
    [7,-3,4],
    [0,2,3]
])

print(m1)

[[ 1  5  9]
 [ 7 -3  4]
 [ 0  2  3]]


In [11]:
# Calculando o determinante, temos:

detm1 = round(np.linalg.det(m1), 2)
detm1

np.float64(4.0)

# 3.0 Sistemas Lineares:

Para resolver um Sistema Linear, poderíamos escrever na forma matricial e solucionar com as ferramentas que vimos utilizando matriz inversa, assim:

$$
\begin{aligned}
A X &= B \\
A^{-1} A X &= A^{-1} B \\
I_n X &= A^{-1} B \\
X &= A^{-1} B
\end{aligned}
$$


O que daria muito trabalho, para facilitar, podemos apenas usar o método solve(). Vamos criar um Sistema Linear e resolver com o solve.

> **Observação:** Embora teoricamente possamos escrever  
> $$
> X=A^{-1}B
> $$
> na prática computacional normalmente evitamos
> calcular a inversa explicitamente. Para resolver sistemas,
> `np.linalg.solve(A, B)` é geralmente a opção preferida.

## 3.1 Com a função solve():

In [23]:
# Criando a Matriz A:

A = np.array([
    [1,2,5,7,-1],
    [1,1,0,5,6],
    [1,0,6,7,9],
    [-1,0.3,0,-2,1],
    [5,6,0,0,1]
])

# Criando a matriz B:

B = np.array([
    [4],
    [3],
    [0],
    [9],
    [-1]
])

In [37]:
# Resolvendo o sistema com o solve:

X_s = np.linalg.solve(A,B)
X_s

array([[-6.83417183],
       [ 5.41530072],
       [ 0.04005323],
       [ 0.06890844],
       [ 0.67905482]])

## 3.2 Com matriz:

In [25]:
# Primeiro, temos que ver se o det A não é zero, assim:

detA = np.linalg.det(A)
detA

np.float64(-3080.9)

In [26]:
# Como não é zero, podemos calcaular a sua inversa:

invA = np.linalg.inv(A)
invA

array([[-0.19182706, -0.19348242,  0.15985589, -0.59560518,  0.12596968],
       [ 0.17137849,  0.15255283, -0.14281541,  0.48135285,  0.06004739],
       [ 0.03411341, -0.21584602,  0.13823883,  0.06361777,  0.02142231],
       [ 0.08705248,  0.14567172, -0.07254374, -0.08504009, -0.04904411],
       [-0.06913564,  0.05209517,  0.05761304,  0.08990879,  0.00986725]])

In [38]:
# Para obter a Matriz X da solução, basta multiplicar A^-1 por B:

X_m = invA@B
X_m

array([[-6.83417183],
       [ 5.41530072],
       [ 0.04005323],
       [ 0.06890844],
       [ 0.67905482]])

In [44]:
# Para fazer uma verificação e comparar arrays, poderíamos fazer:
np.array_equal(X_s, X_m)

False

In [45]:
# porém, como temos muitos números decimais, seria mais fácil certeiro assim:
np.allclose(X_s, X_m)

True